version: "3.8"
services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  api:
    build:
      context: ./minha-api
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: quarkus-api
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ~/.m2:/root/.m2

  frontend:
    build: ./frontend-desafio-ids
    container_name: frontend-desafio-ids
    ports:
      - "4200:80"
    depends_on:
      - api
    volumes:
      - /app/node_modules

volumes:
  postgres_data:
