version: "3.8"
services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./minha-api
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: quarkus-api
    restart: always
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/meu_banco
      QUARKUS_DATASOURCE_USERNAME: meu_usuario
      QUARKUS_DATASOURCE_PASSWORD: minha_senha
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ~/.m2:/root/.m2

  frontend:
    build: ./front-desafio-ids
    container_name: front-desafio-ids
    ports:
      - "4200:80"
    depends_on:
      - api
    volumes:
      - /app/node_modules

volumes:
  postgres_data:
